kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "message-generator.fullname" . }}-reader-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "message-generator.serviceAccountName" . }}
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "message-generator.fullname" . }}-reader-role
  apiGroup: ""