name: Message Generator Main Branch Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PACTFLOW_URL: https://bullyrooks.pactflow.io
  PACTFLOW_TOKEN: ${{secrets.PACTFLOW_TOKEN}}
  PACTBROKER_HOST: bullyrooks.pactflow.io
  GH_TOKEN: ${{secrets.CHART_TOKEN}}

jobs:
  call-get-version:
    uses: bullyrooks/service-workflow/.github/workflows/get-version.yml@main

  call-compile:
    uses: bullyrooks/service-workflow/.github/workflows/compile.yaml@main

  contract-test:
    needs:
      - get-version
    runs-on: ubuntu-latest
    env:
      version: ${{ needs.call-get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Print build number
        run: echo "version=${{ env.version }}"
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Create Pact Version Tag
        run: |
          ./mvnw pact:create-version-tag \
          -Dpacticipant=message-generator \
          -DpacticipantVersion=${{ env.version }} \
          -Dtag=initial

      - name: Verify Contract Tests
        run: |
          ./mvnw -B verify -Pcontract \
          -Dpactbroker.host=${{env.PACTBROKER_HOST}} \
          -Dpact.verifier.publishResults=true \
          -Dpact.provider.version=${{env.version}} \
          -Dpact.provider.branch=main \
          -Dpact.provider.tag=okteto \
          -DPACT_CONSUMER_SELECTOR_TAG=okteto,pre-okteto
        continue-on-error: true #verify may fail, but we're relying on can-i-deploy to control deploy
  can-i-deploy:
    needs:
      - get-version
      - contract-test
    runs-on: ubuntu-latest
    env:
      version:  ${{ needs.get-version.outputs.version }}
    steps:
      - name: Pact Can-i-deploy
        run: |
          echo "VERSION=${{ env.version }}"
          docker run --rm pactfoundation/pact-cli:latest \
          broker can-i-deploy \
          --pacticipant=message-generator  \
          --to-environment=okteto \
          --version=${{ env.version }}  \
          --broker-base-url=${{ env.PACTFLOW_URL }} \
          --broker-token=${{ env.PACTFLOW_TOKEN }}

  call-build-image:
    needs:
      - call-get-version
    uses: bullyrooks/service-workflow/.github/workflows/build-image.yaml@main
    with:
      version: ${{ needs.call-get-version.outputs.version }}

  call-helm-chart:
    needs:
      - build-image
      - can-i-deploy
      - get-version
    uses: bullyrooks/service-workflow/.github/workflows/helm-chart.yaml@main
    with:
      access-token: ${{ secrets.CHART_TOKEN }}
      version: ${{ needs.call-get-version.outputs.version }}

  call-deploy:
    needs:
      - helm-chart
      - get-version
    uses: bullyrooks/service-workflow/.github/workflows/okteto-deploy.yaml@main
    with:
      version: ${{ needs.call-get-version.outputs.version }}
      kube-config: ${{ secrets.KUBECONFIG }}

  pact-release:
    needs:
      - deploy
      - get-version
    runs-on: ubuntu-latest
    env:
      version: ${{ needs.get-version.outputs.version }}
    steps:
      - name: Create Pact Release Record
        run: |
          docker run --rm pactfoundation/pact-cli:latest \
          broker record-release \
          --environment=okteto \
          --pacticipant=message-generator \
          --version=${{ env.version }} \
          --broker-base-url=${{ env.PACTFLOW_URL }} \
          --broker-token=${{ env.PACTFLOW_TOKEN }}

      - name: Create Pact Deployment Record
        run: |
          docker run --rm pactfoundation/pact-cli:latest \
          broker record-deployment \
          --environment=okteto \
          --pacticipant=message-generator \
          --version=${{ env.version }} \
          --broker-base-url=${{ env.PACTFLOW_URL }} \
          --broker-token=${{ env.PACTFLOW_TOKEN }}
